platform :ios, '13'
use_modular_headers!

target 'EthereumKitExample' do
  pod 'EthereumKit.swift', :path => '../'

  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'HdWalletKit.swift', git: 'https://github.com/horizontalsystems/hd-wallet-kit-ios'
end

def testPods
  pod 'Cuckoo'
  pod 'Quick'
  pod 'Nimble'
end

target 'EthereumKitTests' do
  pod 'EthereumKit.swift', :path => '../'
  testPods
end
